spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jpashop
    driver-class-name: org.mariadb.jdbc.Driver
    username: jun
    password: tjgusskavys8*
  jpa:
    database-platform: org.hibernate.dialect.MariaDB10Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true