spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jpql
    driver-class-name: org.mariadb.jdbc.Driver
    username: jun
    password: tjgusskavys8*
  jpa:
    database-platform: org.hibernate.dialect.MariaDB10Dialect
    open-in-view: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create