spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: jun
    password: *